export enum UsersRole {
    SUPERADMINISTRADOR = 1,
    ADMINISTRADORGERENCIAL = 2,
    ADMINISTRADORCONTABLE = 3,
    ADMINISTRADORDEPRODUCCION = 4,
    ADMINISTRADOROPERATIVO = 5,
    USUARIOESTANDAR = 6
}